package com.axiel7.anihyou.release.core.source

enum class ExtensionUpdateState {
    NOT_INSTALLED, INSTALLED_CURRENT, UPDATE_AVAILABLE, CHECKING, DOWNLOADING, VERIFYING,
    STAGING, ACTIVATING, UPDATED, UPDATE_FAILED, ROLLBACK_AVAILABLE, ROLLING_BACK, ROLLED_BACK,
    REVOKED, QUARANTINED, UNUSABLE, TRUST_UNAVAILABLE,
}
enum class InstalledPackageStatus { NOT_INSTALLED, USABLE, REVOKED, QUARANTINED, UNUSABLE, TRUST_UNAVAILABLE }
enum class ExtensionUpdateFailure { NETWORK, TRUST, METADATA, SIGNATURE_OR_BINDING, DIGEST, RUNTIME, SMOKE, ACTIVATION, STORAGE, CANCELLED, INTERRUPTED }
data class ExtensionRollbackTarget(val version: String, val digest: String, val trustState: String = "TRUSTED")

